- hosts: web
  become: true
  vars:
    domain_name: "{{ domain_name | default('example.com') }}"

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX, Node.js, and Certbot
      apt:
        name:
          - nginx
          - nodejs
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy frontend HTML
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Copy backend app
      copy:
        src: backend-app.js
        dest: /home/ubuntu/backend-app.js
        mode: '0755'

    - name: Create systemd service for backend app
      copy:
        dest: /etc/systemd/system/backend.service
        content: |
          [Unit]
          Description=Node.js Backend

          [Service]
          ExecStart=/usr/bin/node /home/ubuntu/backend-app.js
          Restart=always
          User=ubuntu
          Environment=NODE_ENV=production

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start backend service
      systemd:
        name: backend
        enabled: yes
        state: started

    - name: Configure NGINX with reverse proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart NGINX

    - name: Obtain Let's Encrypt certificate for {{ domain_name }}
      command: >
        certbot --nginx -n --agree-tos --redirect
        -m your@email.com
        -d {{ domain_name }}
        -d www.{{ domain_name }}
      when: domain_name is defined

    - name: Test certbot auto-renew
      command: certbot renew --dry-run
      changed_when: false
      ignore_errors: true

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted